name: Code formatting

# Scheduled at 11:30 PM UTC (05:00 AM IST)
# TODO: Replace on: push with cron job
on: push

jobs:
  fix_code_formatting:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Fix code formatting issues
        run: ./gradlew spotlessApply

      - name: Commit and Push
        run: ./scripts/commit_and_push.sh ${{secrets.USER_NAME}} ${{secrets.USER_EMAIL}}

      - name: Create PR
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var monthNames = ["Jan", "Feb", "Mar", "Apr", "May","Jun","Jul", "Aug", "Sep", "Oct", "Nov","Dec"]
            var date = new Date()
            var monthName = monthNames[date.getMonth()]

            var day = `${monthName}-${date.getDate()}-${date.getFullYear()}`
            var branchName = `ga/${day}/code-formatting`
            console.log(branchName)

            await github.pulls.create({
              ...context.repo,
              title: 'Code formatting fixes',
              head: 'code-formatting',
              base: 'master'
            })
